proxy:
  title: Surreal DBLink DDBJ
#  hide-navbar: true
  landing-page: /app/surrealview
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  port: 3201
  authentication: none
  container-wait-time: 120000
  docker:
    internal-networking: true
#    port-range-start: 20000
#    port-range-max: 21000
  specs:
  - id: surrealview
    display-name: DBLINK_DDBJ_Surreal_Viewer
    description: DBLINK DDBJ Reviewer WebPage
    container-cmd: ["R", "-e", "shiny::runApp('R/surrealViewApp.R', port=3838, host='0.0.0.0')"]
    container-image: ghelfi/surreal_view_app_light
    container-network: surrealnet
    container-volumes: [ "db_master:/usr/local/src/app/data"]
spring:
  servlet:
    multipart:
      max-file-size: 400MB
      max-request-size: 400MB
logging:
  file:
    shinyproxy.log
server:
  servlet.session.timeout: 18000
